services:
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - 5555:5432
  movies:
    build:
      context: .
      dockerfile: ./apps/movies/Dockerfile
      target: development
    command: npm run start:dev movies
    environment:
      - WATCHPACK_POLLING=true
    env_file:
      - .env
    ports:
      - 3001:3001
    volumes:
      - .:/app
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    environment:
      - WATCHPACK_POLLING=true
    env_file:
      - .env
    ports:
      - 3002:3002
    volumes:
      - .:/app
  cinema:
    build:
      context: .
      dockerfile: ./apps/cinema/Dockerfile
      target: development
    command: npm run start:dev cinema
    environment:
      - WATCHPACK_POLLING=true
    env_file:
      - .env
    ports:
      - 3003:3003
    volumes:
      - .:/app