services:
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - 5555:5432
  redis:
    image: redis
    ports:
      - 6379:6379
  main:
    build:
      context: .
      dockerfile: ./apps/main/Dockerfile
      target: development
    command: npm run start:dev main
    environment:
      - WATCHPACK_POLLING=true
    env_file:
      - .env
    ports:
      - 3001:3001
    volumes:
      - .:/app
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    environment:
      - WATCHPACK_POLLING=true
    env_file:
      - .env
    ports:
      - 3002:3002
    volumes:
      - .:/app
  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: npm run start:dev notifications
    environment:
      - WATCHPACK_POLLING=true
    env_file:
      - .env
    ports:
      - 3003:3003
    volumes:
      - .:/app