services:
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - 2345:5432
  movies:
    build:
      context: .
      dockerfile: ./apps/movies/Dockerfile
      target: development
    command: npm run start:dev movies
    ports:
      - 3000:3000
    volumes:
      - .:/app