services:
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - 2345:5432
  movies:
    build:
      context: .
      dockerfile: ./apps/movies/Dockerfile
      target: development
    command: npm run start:dev movies
    environment:
      - WATCHPACK_POLLING=true
    env_file:
      - .env
    ports:
      - 3001:3001
    volumes:
      - .:/app