apiVersion: v1
kind: Service
metadata:
  labels:
    app: main
  name: main
spec:
  ports:
  - name: "http"
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: main
  type: NodePort
