apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: movies
  name: movies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
        - image: europe-west3-docker.pkg.dev/cinema-426911/movies/production
          name: movies
          env: 
            - name: POSTGRES_DB
              value: cinema
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_HOST
              value: ep-curly-haze-a22zi5aj.eu-central-1.aws.neon.tech
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-username-secret
                  key: postgres-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password-secret
                  key: postgres-password
          ports:
            - containerPort: 3001
