apiVersion: v1
kind: Service
metadata:
  labels:
    app: movies
  name: movies
spec:
  ports:
    - name: 'http'
      port: 3004
      protocol: TCP
      targetPort: 3001
  selector:
    app: movies
  type: NodePort